[project]
name = "sxpb_llm_benchmark"
version = "0.0.0"
authors = [
]
dependencies = [
    "pyyaml>=6.0.3",
    "llama-cpp-python>=0.3.16",
    "huggingface-hub>=0.20.3",
    "psutil>=5.9.8",
    "openai>=1.0.0",
    "sxpb @ git+https://github.com/sxproto/sxpb-py@1fe75aaf846de33f7408d9663c6d0172feb718b9",
]
requires-python = ">=3.9"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "ruff",
    "ty",
    "faker",
]

[tool.pytest.ini_options]
addopts = "--showlocals"
pythonpath = ["."]


[tool.pdm.scripts]
benchmark = "python -m src.run_benchmark"
toon-benchmark = "python -m src.run_toon_benchmark"
check-format = "ruff check"
check-type = "ty check"
tidy = "ruff format"
lint = {composite = ["check-format", "check-type"]}
test = "pytest"
