[project]
name = "sxpb_llm_benchmark"
version = "0.0.0"
authors = [
]
dependencies = [
    "openai>=1.0.0",
    "pyyaml>=6.0.3",
    "sxpb @ git+https://github.com/sxproto/sxpb-py@04fbc53342cb7c7dd75166be955253711966f5e2",
]
requires-python = ">=3.9"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "ruff",
    "ty",
]

[tool.pytest.ini_options]
addopts = "--showlocals"
pythonpath = ["."]


[tool.pdm.scripts]
benchmark = "python -m src.run_benchmark"
q2a = "python -m src.q2a"
check-format = "ruff check"
check-type = "ty check"
tidy = "ruff format"
lint = {composite = ["check-format", "check-type"]}
test = "pytest"
tidytest = {composite = ["test", "tidy", "lint"]}
