name: CI

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PDM
      run: pip install pdm
    - name: Install dependencies
      run: pdm install
    - name: Run lint
      run: pdm run lint
    - name: Run tests
      run: pdm run test
